### ISSUE TITLE
Payfort validate the response return on the Return-URL and host to host URL

### ISSUE THREAD

**Issue by sanjeev1153** [payfort/php-payfort#6]
How can I integrate host to host url in payfort?
payfort sent a message : Please make sure that you are handle the response parameters we are sending on the Host to Host URL ?

**Comment by mohannadsaleh** [comment]
PHP library mainly handle the redirection and receive parameters , in order to handle the response codes and statuses u can contact our integration team integration@payfort.com

Note : within the next 2 months we will launch a new php library which will include more control on handling responses and to support other integration types .
